// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MaximiseApp():Promise<void>;

export function MinimiseApp():Promise<void>;

export function QuitApp():Promise<void>;
